alias update_dotfiles='sh -c "$(curl -fsSL https://raw.githubusercontent.com/swaaws/dotfiles/master/dotfiles.sh)"'
alias ll='ls -la'
alias lh='ls -lah'
alias wan4='dig @resolver1.opendns.com A myip.opendns.com +short -4'
alias wan6='dig @resolver1.opendns.com AAAA myip.opendns.com +short -6'
